#!/bin/sh
# One-off: creates the initial migration from the current schema and checks that the live database
# (created with `prisma db push`) matches it exactly, so it can be marked as already applied.
set -e
cd /app
mkdir -p prisma/migrations/0_init
npx prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script > prisma/migrations/0_init/migration.sql
cat > prisma/migrations/migration_lock.toml <<'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
EOF
echo "migration lines: $(wc -l < prisma/migrations/0_init/migration.sql)"
set +e
npx prisma migrate diff --from-config-datasource --to-schema prisma/schema.prisma --exit-code > /tmp/drift.txt
code=$?
set -e
echo "drift exit code: $code (0 = identical, 2 = differences)"
head -30 /tmp/drift.txt
