// Catalogue of acceptance scenarios: ID -> [module, précondition, action, résultat attendu, priorité].
// The executable scenario is the Playwright test whose title starts with "[ID]".
export const CATALOG = {
  'SMK-01': ['Déploiement', 'Stack déployée', 'GET /api/health', '200, status ok', 'P0'],
  'SMK-02': ['Déploiement', 'Stack déployée', 'GET /api/health/ready', 'Base joignable, version exposée', 'P0'],
  'SMK-03': ['Déploiement', 'Stack déployée', 'GET /login', '200, page en français', 'P0'],
  'SMK-04': ['Déploiement', 'Seed chargé', 'Connexion des 7 rôles', 'Jeton pour chaque rôle', 'P0'],
  'SMK-05': ['Déploiement', 'Migrations appliquées', 'GET /school/settings', 'Nouveau schéma présent (plan)', 'P0'],
  'AUTH-01': ['Authentification', 'Compte directeur actif', 'Connexion email + mot de passe', 'Jeton + profil, aucun hash', 'P0'],
  'AUTH-02': ['Authentification', 'Compte existant', 'Mauvais mot de passe', '401, message générique', 'P0'],
  'AUTH-03': ['Authentification', '—', 'Email inconnu', '401, même message (pas d’énumération)', 'P0'],
  'AUTH-04': ['Authentification / session', '—', 'Appel sans jeton / jeton falsifié', '401', 'P0'],
  'AUTH-05': ['Authentification', 'Compte créé pour le test', 'Mot de passe oublié → email → reset', 'Réponse identique compte connu/inconnu, lien unique 15 min, nouveau mdp actif, ancien refusé', 'P0'],
  'AUTH-06': ['Authentification / MFA', 'Compte comptable créé', 'Activation TOTP puis connexion en 2 étapes', 'Code faux refusé, jeton intermédiaire non utilisable, code valide accepté', 'P0'],
  'AUTH-07': ['Authentification / session', 'École 2 active', 'Suspension puis réactivation de l’école', 'Accès coupé immédiatement puis rétabli', 'P0'],
  'MT-01': ['Multi-tenant', 'Opérateur connecté', 'Création d’une école', 'Tenant vide isolé, année créée, email au directeur, connexion OK', 'P0'],
  'MT-02': ['Multi-tenant', '2 écoles', 'Directeur B lit/modifie/supprime un élève de A', '403 partout, absent de la liste', 'P0'],
  'MT-03': ['Multi-tenant', '2 écoles', 'Écritures avec identifiants de A depuis B', 'Refusées (400/404)', 'P0'],
  'MT-04': ['Multi-tenant', 'Même matricule dans 2 écoles', 'Recherche par matricule', 'Deux élèves distincts, chacun dans son école', 'P1'],
  'MT-05': ['Multi-tenant / branding', 'Directeur', 'Couleur illisible puis lisible', '400 contraste ; couleur appliquée au profil', 'P1'],
  'MT-06': ['Multi-tenant / feature flags', 'École Starter', 'Module hors plan, exception, retrait', '404 → 200 → 404', 'P0'],
  'MT-07': ['Multi-tenant', 'Opérateur plateforme', 'Lecture de données d’école', '403 sur toutes les routes métier', 'P0'],
  'MT-08': ['Multi-tenant / domaines', '—', 'Résolution sous-domaine', 'Code école ; hôte inconnu 404', 'P1'],
  'RBAC-01': ['Permissions', 'Enseignant', 'Paie, factures, salaires, finances', '403 ; salaires et finances masqués', 'P0'],
  'RBAC-02': ['Permissions', 'Parent', 'Routes de gestion, enfant d’autrui', '403 ; seulement ses enfants', 'P0'],
  'RBAC-03': ['Permissions', 'Élève', 'Routes de gestion', '403', 'P0'],
  'RBAC-04': ['Permissions', 'Secrétaire', 'Paie ; inscription élève', '403 ; 201', 'P0'],
  'RBAC-05': ['Permissions', 'Comptable', 'Salaires, fiche élève', 'Salaires visibles, notes masquées', 'P1'],
  'RBAC-06': ['Sécurité', 'Directeur', 'Réponses classes/personnel/paie', 'Aucun hash bcrypt', 'P0'],
  'ST-01': ['Élèves', 'Classes existantes', 'Inscription', 'Matricule séquentiel AAAA-NNNN', 'P0'],
  'ST-02': ['Élèves', 'Élèves existants', 'Recherche + pagination', 'Résultat + X-Total-Count', 'P1'],
  'ST-03': ['Élèves', 'Élève inscrit', 'Modification + transfert de classe', 'Nouvelle classe active', 'P1'],
  'ST-04': ['Élèves', '2 écoles', 'Inscription dans une classe étrangère', '404', 'P0'],
  'PA-01': ['Parents', 'Élève existant', 'Création parent rattaché', 'Lien parent ↔ enfant', 'P1'],
  'PA-02': ['Parents / notifications', 'Parent avec compte', 'Absence saisie par l’enseignant', 'Notification au parent', 'P1'],
  'CL-01': ['Classes', 'Directeur', 'Création, modification, enseignant étranger, suppression', '201/200/404/200', 'P1'],
  'AD-01': ['Admissions', 'Directeur', 'Candidature → INSCRIPTION', 'Élève créé avec matricule', 'P1'],
  'GR-01': ['Notes', 'Enseignant', 'Saisie ; élève non inscrit', '201 ; 400', 'P0'],
  'GR-02': ['Bulletins', 'Notes saisies', 'Calcul + PDF', 'Moyenne, rang, PDF valide', 'P0'],
  'TT-01': ['Emplois du temps', 'Matières + heures', 'Génération toutes classes avec contrainte', 'Tout placé, 0 conflit, créneau libéré respecté', 'P0'],
  'TT-02': ['Emplois du temps', 'Classe B publiée', 'Conflit enseignant introduit à la main', 'Conflit détecté, publication refusée', 'P0'],
  'TT-03': ['Emplois du temps', 'Brouillon', 'Régénération + publication', '0 conflit, enseignants notifiés', 'P0'],
  'TT-04': ['Emplois du temps', 'EDT publié', 'Export CSV + ICS', 'Fichiers valides (RRULE hebdo)', 'P1'],
  'TT-05': ['Emplois du temps', 'Enseignant', 'Mon EDT ; génération', 'Cours visibles ; 403', 'P1'],
  'FI-01': ['Finance', 'Comptable', 'Facture', 'Référence INV-AAAA-NNNNN', 'P0'],
  'FI-02': ['Finance', 'Facture', 'Paiement partiel Mobile Money', 'PARTIALLY_PAID', 'P0'],
  'FI-03': ['Finance', 'Facture partiellement payée', 'Sur-paiement', '400 avec reste à payer', 'P0'],
  'FI-04': ['Finance / relances', 'Facture échue', 'Liste des impayés + relances', 'Facture listée, OVERDUE, parents notifiés', 'P1'],
  'FI-05': ['Finance / rapports', 'Factures + paiements', 'Statistiques', 'Impayés = facturé − encaissé', 'P1'],
  'FI-06': ['Paie', 'Salaires définis', 'Génération → ajustement → validation → paiement → PDF', 'Cycle complet, bulletin payé verrouillé', 'P0'],
  'CO-01': ['Communication', 'Directeur', 'Annonce publiée', 'Visible sur la vitrine', 'P1'],
  'VI-01': ['Vitrine', 'Vitrine publiée', 'Préinscription publique', 'Dossier créé + accusé email', 'P0'],
  'VI-02': ['Vitrine / anti-spam', '—', 'Champ piège rempli', 'Ignoré silencieusement', 'P1'],
  'VI-03': ['Vitrine', '—', 'Formulaire de contact', 'Message reçu par l’école', 'P1'],
  'VI-04': ['Vitrine / constructeur', 'Directeur', 'Masquer une section', 'Retirée de la vitrine', 'P1'],
  'VI-05': ['Vitrine / sécurité', 'Directeur', 'URL javascript:', '400', 'P0'],
  'VI-06': ['Vitrine', '—', 'École inexistante', '404', 'P2'],
  'DO-01': ['Documents', 'Première ouverture', 'Liste des modèles', '3 modèles fournis', 'P1'],
  'DO-02': ['Documents / IA d’import', 'Modèle Word collé', 'Analyse', 'Correspondances [Nom élève]→variables', 'P1'],
  'DO-03': ['Documents', 'Élève existant', 'Génération certificat + vérification publique', 'Numéro, QR, page publique sans données personnelles', 'P0'],
  'DO-04': ['Documents / sécurité', 'Directeur', 'Script dans un modèle', 'Supprimé ; CSP stricte', 'P0'],
  'DO-05': ['Documents / versioning', 'Document émis', 'Nouvelle version du modèle', 'Anciens documents inchangés', 'P1'],
  'SEC-01': ['Sécurité', '—', 'En-têtes HTTP', 'nosniff, CSP, HSTS, pas de X-Powered-By', 'P0'],
  'SEC-02': ['Sécurité', 'Production', 'GET /api/docs', '404', 'P1'],
  'SEC-03': ['Sécurité / injection', 'Directeur', 'Recherche "\' OR 1=1 --"', '200, aucun résultat', 'P0'],
  'SEC-04': ['Sécurité / XSS', 'Nom d’élève piégé', 'Document généré', 'Contenu échappé', 'P0'],
  'SEC-05': ['Sécurité', 'Directeur', 'Paramètre invalide', '400 sans trace technique', 'P1'],
  'SEC-06': ['Sécurité', 'Directeur', 'Champ non prévu (schoolId)', '400', 'P0'],
  'SEC-07': ['Sécurité / audit', 'Actions réalisées', 'Journal d’audit', 'Actions sensibles tracées, sans secret ; enseignant 403', 'P0'],
  'SEC-08': ['Sécurité / rate limiting', '—', '12 requêtes / minute', '429', 'P0'],
  'IA-01': ['IA / droits', 'Directeur, enseignant', 'Outils proposés', 'Enseignant sans outils paie/finance', 'P0'],
  'IA-02': ['IA / plans', 'École Starter, parent', 'Chat', '404 ; 403', 'P0'],
  'IA-03': ['IA / recherche', 'Clé API', '« Combien d’élèves ont des impayés ? »', 'Outil impayés appelé, réponse chiffrée', 'P1'],
  'IA-04': ['IA / refus', 'Enseignant', '« Donne-moi les salaires… »', 'Aucune donnée de paie', 'P0'],
  'IA-05': ['IA / action sensible', 'Directeur', '« Crée une classe… »', 'En attente, rien créé avant confirmation, confirmation unique', 'P0'],
  'IA-06': ['IA / injection', 'Enseignant', 'Consigne malveillante', 'Aucun outil hors droits exécuté', 'P0'],
  'IA-07': ['IA / interface dynamique', 'Directeur', '« Tableau de bord des impayés »', 'Vue validée, enregistrée, données relues', 'P1'],
  'IA-08': ['IA / interface dynamique', '—', 'Spécification invalide / source interdite', 'Refusée', 'P0'],
  'IA-09': ['IA / emplois du temps', 'Directeur', 'Demande d’EDT en langage naturel', 'Brouillon à confirmer', 'P1'],
  'IA-10': ['IA / audit', 'Échanges réalisés', 'Journal', 'CHAT et PROPOSE tracés', 'P1'],
  'PF-01': ['Performance', 'Données de démo', '30 lectures × 7 routes', 'p95 < 300 ms', 'P1'],
  'PF-02': ['Performance / volume', '+300 élèves', 'Liste paginée, recherche, tableau de bord', '< 500 ms chacun', 'P1'],
  'PF-03': ['Performance', 'Toutes classes', 'Génération EDT', '< 3 s', 'P2'],
  'PF-04': ['Performance', 'Modèle', 'Génération document', '< 3 s', 'P2'],
  'UI-01': ['Interface / authentification', 'Navigateur bureau', 'Connexion, déconnexion, page protégée', 'Redirections correctes', 'P0'],
  'UI-02': ['Interface / authentification', '—', 'Mauvais identifiants', 'Message annoncé (role=alert)', 'P1'],
  'UI-03': ['Interface / tableau de bord', 'Directeur', 'Tableau de bord + axe', 'KPI + finances, 0 violation grave', 'P0'],
  'UI-04': ['Interface / permissions', 'Enseignant', 'Tableau de bord + menu', 'Pas de finances, menu restreint', 'P0'],
  'UI-05': ['Interface / élèves', 'Directeur', 'Création via modale (Échap)', 'Élève créé, modale accessible, 0 violation', 'P0'],
  'UI-06': ['Interface / permissions', 'Enseignant', 'Écran élèves', 'Bouton de création absent', 'P1'],
  'UI-07': ['Interface / présences', 'Enseignant', 'Appel', 'Enregistré', 'P0'],
  'UI-08': ['Interface / notes', 'Enseignant', 'Écran de saisie', 'Grille affichée', 'P0'],
  'UI-09': ['Interface / facturation', 'Comptable', 'Relance des impayés', 'Bandeau de résultat', 'P1'],
  'UI-10': ['Interface / paie', 'Comptable', 'Écran paie + axe', '0 violation grave', 'P1'],
  'UI-11': ['Interface / EDT', 'EDT publié', 'Grille + export CSV', 'Téléchargement .csv', 'P1'],
  'UI-12': ['Interface / documents', 'Directeur', 'Aperçu certificat', 'Iframe isolée (sandbox)', 'P1'],
  'UI-13': ['Interface / vitrine', 'Directeur', 'Paramètres + contraste + axe', 'Indicateur lisible, sections, 0 violation', 'P1'],
  'UI-14': ['Interface / audit', 'Directeur', 'Journal d’audit', 'Entrées PAYMENT visibles', 'P1'],
  'UI-15': ['Interface / plateforme', 'Opérateur', 'Console', 'Écoles listées, pas de menu métier', 'P0'],
  'UI-16': ['Vitrine / SEO', '—', 'HTML serveur', 'title, og:title, contenu sans JS', 'P1'],
  'UI-17': ['Vitrine / sous-domaine', '—', 'demo-001.localhost', 'Vitrine de l’école', 'P1'],
  'UI-18': ['Vitrine / préinscription', '—', 'Formulaire public', 'Confirmation annoncée', 'P0'],
  'UI-19': ['Documents / vérification', '—', 'Code inconnu', 'Message d’alerte', 'P2'],
  'UI-20': ['Interface / portail parent', 'Parent', 'Portail + axe', '0 violation grave', 'P0'],
  'UI-21': ['Accessibilité', 'Directeur', 'Tab au chargement', 'Lien d’évitement focalisé', 'P1'],
  'UI-22': ['Accessibilité', '—', 'axe sur pages publiques', '0 violation grave', 'P1'],
  'UI-23': ['Sécurité web', '—', 'En-têtes des pages', 'CSP, X-Frame-Options, nosniff, Permissions-Policy, pas de X-Powered-By', 'P0'],
  'MO-01': ['Mobile', 'Tablette/téléphone', 'Connexion', 'Pas de défilement horizontal', 'P0'],
  'MO-02': ['Mobile', 'Téléphone', 'Barre inférieure + « Plus »', 'Navigation fonctionnelle', 'P0'],
  'MO-03': ['Mobile / présences', 'Enseignant', 'Appel', 'Utilisable sans défilement horizontal', 'P0'],
  'MO-04': ['Mobile / portail parent', 'Parent', 'Portail', 'Utilisable', 'P0'],
  'MO-05': ['Mobile', 'Directeur', 'Tableau de bord, élèves', 'Pas de défilement horizontal', 'P1'],
  'MO-06': ['Mobile / vitrine', '—', 'Vitrine', 'Appel à l’action visible, pas de défilement horizontal', 'P1'],
  'MO-07': ['Mobile', 'Directeur', 'Assistant, documents', 'Atteignables', 'P1'],
  'MO-08': ['Mobile', 'Directeur', 'Modale', 'Feuille basse, bouton Fermer', 'P2'],
};
